import pandas as pd
import sys
import math

# Usage: python3 otp_info_gen.py <xlsx file> <output_header_file>

def parse_bit_string(bit_str):
    if ':' in bit_str:
        parts = bit_str.split(':')
        return int(parts[0]), int(parts[1])
    else:
        return int(bit_str), int(bit_str)

import re

def format_desc(desc):
    desc_str = str(desc).strip()

    parts0 = re.split(r'\s*0\s*:', desc_str)
    if parts0[0].strip():
        desc_str = parts0[0].strip()

    parts = desc_str.replace('\n', '. ').split('. ')
    first_sentence = parts[0].strip()
    return first_sentence.replace('"', '\\"')

def get_desc_en_dis(desc_raw):
    desc_str = str(desc_raw).strip().replace('"', '\\"')

    parts0 = re.split(r'\s*0\s*:', desc_str)
    prefix_text = parts0[0].strip().lower()

    # If the prefix text already contains enable/disable, it's a perfect boolean title! Ignore 0:/1: verbosity.
    if "enable" not in prefix_text and "disable" not in prefix_text:
        if ('0:' in desc_str or '0 : ' in desc_str) and ('1:' in desc_str or '1 : ' in desc_str):
            m0 = re.search(r'0\s*:\s*(.*?)(?=\s*1\s*:|\n|$)', desc_str, re.IGNORECASE)
            m1 = re.search(r'1\s*:\s*(.*?)(?=\s*0\s*:|\n|$)', desc_str, re.IGNORECASE)
            if m0 and m1:
                desc0 = m0.group(1).strip('., \t\n')
                desc1 = m1.group(1).strip('., \t\n')
                if desc0.lower() not in ["enable", "disable", "valid", "invalid"] and \
                   desc1.lower() not in ["enable", "disable", "valid", "invalid"]:
                    prefix_title = format_desc(desc_raw)
                    prefix_title = re.sub(r"\s*b'?[01]*\s*$", "", prefix_title).strip()
                    if prefix_title:
                        return f"{prefix_title}: {desc1}", f"{prefix_title}: {desc0}"
                    else:
                        return desc1, desc0

    first_sentence = format_desc(desc_raw)

    if "Disable" in first_sentence:
        return first_sentence, first_sentence.replace("Disable", "Enable")
    elif "disable" in first_sentence:
        return first_sentence, first_sentence.replace("disable", "enable")
    elif "DISABLE" in first_sentence:
        return first_sentence, first_sentence.replace("DISABLE", "ENABLE")
    elif "Enable" in first_sentence:
        return first_sentence, first_sentence.replace("Enable", "Disable")
    elif "enable" in first_sentence:
        return first_sentence, first_sentence.replace("enable", "disable")
    elif "ENABLE" in first_sentence:
        return first_sentence, first_sentence.replace("ENABLE", "DISABLE")
    else:
        return first_sentence, first_sentence

def main():
    if len(sys.argv) < 3:
        print("Usage: python3 otp_info_gen.py <xlsx_file> <output_file>")
        sys.exit(1)

    xlsx_path = sys.argv[1]
    out_path = sys.argv[2]

    sheets = {
        'OTPCFG': 'a2_conf_info',
        'OTPSTRAP': 'a2_strap_info',
        'OTPSTRAP_EXT': 'a2_strap_ext_info',
        'OTPCAL': 'a2_cal_info',
        'OTPRBP': 'a2_rbp_info'
    }

    with open(out_path, 'w') as f:
        f.write("/* Generated by otp_info_gen.py */\n\n")

        for sheet, arr_name in sheets.items():
            print(f"Processing {sheet}...")
            df = pd.read_excel(xlsx_path, sheet_name=sheet)

            # Clean dataframe
            df = df.dropna(subset=['Start address (word)', 'Name'])
            if df.empty:
                continue
            if sheet == 'OTPSTRAP':
                base_w_offset = int('422', 16)
            elif sheet == 'OTPSTRAP_EXT':
                base_w_offset = int('431', 16)
            else:
                base_w_offset = int(str(df['Start address (word)'].iloc[0]), 16)

            def is_unwanted(r):
                text = (str(r.get('Name', '')) + ' ' + str(r.get('Description', ''))).lower()
                if 'duplicate of' in text: return True
                if 'ecc/brp' in text: return True
                if 'otpstrap_ext source valid' in text: return True
                if 'write protection of otpstrap' in text: return True
                return False

            df = df[~df.apply(is_unwanted, axis=1)]

            df = df[df['Name'] != 'Reserved']
            df = df[df['Name'] != 'Sum']
            df = df[df['Name'] != 'Actual']
            df = df[df['Name'] != 'PUF']

            if df.empty:
                continue

            if sheet == 'OTPCFG':
                struct_name = 'otpconf_info'
            elif sheet == 'OTPSTRAP':
                struct_name = 'otpstrap_info'
            elif sheet == 'OTPSTRAP_EXT':
                struct_name = 'otpstrap_ext_info'
            elif sheet == 'OTPCAL':
                struct_name = 'otpcal_info'
            else:
                struct_name = 'otprbp_info'

            f.write(f"static const struct {struct_name} {arr_name}[] = {{\n")

            for _, row in df.iterrows():
                try:
                    addr_val = row['Start address (word)']
                    w_offset = int(str(addr_val), 16) - base_w_offset

                    desc = format_desc(row['Description'])
                    if str(desc) == "nan":
                        desc = format_desc(row['Name'])

                    bit_str = str(row['Bit']).strip()
                    end_bit, start_bit = parse_bit_string(bit_str)
                    length = end_bit - start_bit + 1

                    if sheet == 'OTPRBP':
                        f.write(f"\t{{ {w_offset}, {length}, \"{desc}\" }},\n")
                    elif sheet == 'OTPCFG':
                        if length == 1:
                            desc_en, desc_dis = get_desc_en_dis(row['Description'])
                            if str(desc_en) == "nan" or not desc_en:
                                desc_en = format_desc(row['Name'])
                                desc_dis = desc_en
                            f.write(f"\t{{ {w_offset}, {start_bit}, 1, 1, \"{desc_en}\" }},\n")
                            f.write(f"\t{{ {w_offset}, {start_bit}, 1, 0, \"{desc_dis}\" }},\n")
                        else:
                            f.write(f"\t{{ {w_offset}, {start_bit}, {length}, OTP_REG_VALUE, \"{desc}: 0x%x\" }},\n")
                    elif sheet in ['OTPSTRAP', 'OTPSTRAP_EXT']:
                        accumulated_bit = w_offset * 16 + start_bit

                        if length == 1:
                            desc_en, desc_dis = get_desc_en_dis(row['Description'])
                            if str(desc_en) == "nan" or not desc_en:
                                desc_en = format_desc(row['Name'])
                                desc_dis = desc_en
                            f.write(f"\t{{ {accumulated_bit}, 1, 1, \"{desc_en}\" }},\n")
                            f.write(f"\t{{ {accumulated_bit}, 1, 0, \"{desc_dis}\" }},\n")
                        elif length <= 5:
                            for val in range(2**length):
                                f.write(f"\t{{ {accumulated_bit}, {length}, {val}, \"{desc}\" }},\n")
                        else:
                            f.write(f"\t{{ {accumulated_bit}, {length}, OTP_REG_VALUE, \"{desc}: 0x%x\" }},\n")
                    elif sheet == 'OTPCAL':
                        # OTPCAL info: { int w_offset; signed char bit_offset; int length; int value; const char *information; }
                        if length == 1:
                            desc_en, desc_dis = get_desc_en_dis(row['Description'])
                            if str(desc_en) == "nan" or not desc_en:
                                desc_en = format_desc(row['Name'])
                                desc_dis = desc_en
                            f.write(f"\t{{ {w_offset}, {start_bit}, 1, 1, \"{desc_en}\" }},\n")
                            f.write(f"\t{{ {w_offset}, {start_bit}, 1, 0, \"{desc_dis}\" }},\n")
                        else:
                            f.write(f"\t{{ {w_offset}, {start_bit}, {length}, OTP_REG_VALUE, \"{desc}: 0x%x\" }},\n")

                except Exception as e:
                    print(f"Error parsing row in {sheet}: {row['Name']} - {e}")
            f.write("};\n\n")

if __name__ == '__main__':
    main()
